-- VHDL Entity MIPS.MIPS_tb.symbol
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:45 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--


ENTITY MIPS_tb IS
-- Declarations

END MIPS_tb ;

--
-- VHDL Architecture MIPS.MIPS_tb.struct
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:45 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

LIBRARY work;

ARCHITECTURE struct OF MIPS_tb IS

   -- Architecture declarations

   -- Internal signal declarations
			 
	CONSTANT MemWidth	: INTEGER := 8;
	CONSTANT SIM 		: BOOLEAN := TRUE;
  
	SIGNAL clock           : STD_LOGIC;
	SIGNAL reset           : STD_LOGIC;
	SIGNAL ena			   : STD_LOGIC; 
	SIGNAL ena_INPUT	   : STD_LOGIC;
	SIGNAL BreakPoint			   : STD_LOGIC;
	SIGNAL PBADD		   : STD_LOGIC_VECTOR( 7 DOWNTO 0 );
	--SIGNAL PCOut           : STD_LOGIC_VECTOR( 9 DOWNTO 0 );
	--SIGNAL ALU_result_out  : STD_LOGIC_VECTOR( 31 DOWNTO 0 );
	--SIGNAL Instruction_out : STD_LOGIC_VECTOR( 31 DOWNTO 0 );
	--SIGNAL write_data_out  : STD_LOGIC_VECTOR( 31 DOWNTO 0 );


   -- Component Declarations
   COMPONENT MIPS
		GENERIC (MemWidth	: INTEGER := 8;
				 SIM 		: BOOLEAN := TRUE);
		PORT( 
			ena					: IN 	STD_LOGIC := '1'; 
			ena_INPUT			: IN 	STD_LOGIC := '0';
			reset				: IN 	STD_LOGIC := '0';
			clock				: IN 	STD_LOGIC; 
			PBADD				: IN 	STD_LOGIC_VECTOR( 7 DOWNTO 0 );
			BreakPoint			: OUT 	STD_LOGIC
		);
   END COMPONENT;
   
   COMPONENT MIPS_tester
		PORT( 
			reset, clock					: OUT 	STD_LOGIC; 
			ena								: OUT 	STD_LOGIC; 
			ena_INPUT						: OUT 	STD_LOGIC;
			PBADD							: OUT 	STD_LOGIC_VECTOR( 7 DOWNTO 0 );
			BreakPoint						: IN 	STD_LOGIC
		);
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : MIPS USE ENTITY work.mips;
   FOR ALL : MIPS_tester USE ENTITY work.mips_tester;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : MIPS
	  GENERIC MAP (MemWidth 	=> MemWidth,
					SIM 		=> SIM
	  )
      PORT MAP (
         reset           => reset,
         clock           => clock,
		 ena_INPUT		 => ena_INPUT,
		 ena			 => ena,
		 BreakPoint		 => BreakPoint,
		 PBADD			 => PBADD
      );
   U_1 : MIPS_tester
      PORT MAP (
		 PBADD			 => PBADD,
		 BreakPoint		 => BreakPoint,
        -- write_data_out  => write_data_out,
		 ena_INPUT		 => ena_INPUT,
		 ena			 => ena,
         clock           => clock,
         reset           => reset
      );

END struct;
