-- VHDL Entity MIPS.MIPS_tester.interface
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:44 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

ENTITY mcu_tester IS
   PORT( 

			Switches            	: OUT   		STD_LOGIC_VECTOR(7 DOWNTO 0);
        	--AddressBus 	        	: out 	STD_LOGIC_VECTOR(11 DOWNTO 0);
			--dataBus     			: OUT 	STD_LOGIC_VECTOR(31 DOWNTO 0);
			LED_G,LED_R 			: IN   	STD_LOGIC_VECTOR(7 DOWNTO 0);
			HEX0,HEX1,HEX2,HEX3 	: IN   	STD_LOGIC_VECTOR(6 DOWNTO 0);
			--clock_master          	: OUT    STD_LOGIC ;
			clock					: OUT	STD_LOGIC;
			reset           		: OUT    STD_LOGIC;
			KEY3, KEY2				: OUT STD_LOGIC;
			enable					: out STD_LOGIC;
			KEY1					: OUT STD_LOGIC
			
			
   );

-- Declarations

END mcu_tester ;

--
-- VHDL Architecture MIPS.MIPS_tester.struct
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:44 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;


ARCHITECTURE struct OF mcu_tester IS

   -- Architecture declarations

   -- Internal signal declarations


   -- ModuleWare signal declarations(v1.9) for instance 'U_0' of 'clk'
   SIGNAL mw_U_0clk : std_logic;
   SIGNAL mw_U_0disable_clk : boolean := FALSE;

   -- ModuleWare signal declarations(v1.9) for instance 'U_1' of 'pulse'
   SIGNAL mw_U_1pulse : std_logic ;


BEGIN
	Switches <= X"AA";
	enable 	<= '1';
	--KEY0 <= '1' ;
	KEY1 <= '1' ;
	KEY2 <= '1' ; 
	KEY3 <= '1' ;
   -- ModuleWare code(v1.9) for instance 'U_0' of 'clk'
   u_0clk_proc: PROCESS
   BEGIN
      WHILE NOT mw_U_0disable_clk LOOP
         mw_U_0clk <= '0', '1' AFTER 50 ns;
         WAIT FOR 100 ns;
      END LOOP;
      WAIT;
   END PROCESS u_0clk_proc;
   mw_U_0disable_clk <= TRUE AFTER 20000000 ns;
   clock <= mw_U_0clk;

   -- ModuleWare code(v1.9) for instance 'U_1' of 'pulse'
   reset <= mw_U_1pulse;
   u_1pulse_proc: PROCESS
   BEGIN
      mw_U_1pulse <= '1',
         '0' AFTER 50 ns,
         '1' AFTER 210 ns,
		 '0' AFTER 10210 ns,
		 '1' AFTER 10350 ns
			;

      WAIT;
    END PROCESS u_1pulse_proc;
	
	
	


   -- Instance port mappings.

END struct;
